### ISSUE TITLE
Make distro not working

### ISSUE THREAD

**Issue by wilsonk** [vlang/vos#36]
I just pulled the repo today (upgrade mlibc - d6bd12987ba0d660c8bd8a47c59b0c2647075b2a) and tried to build on an Arch based distro of Linux. I had the same errors in the wget subdir when trying to build with both clang-12.0.1 and gcc-11.1.0:

```
/home/wilsonk/Downloads/vinix/build/../3rdparty/wget/lib/c-strcasecmp.c: In function 'c_strcasecmp':
/home/wilsonk/Downloads/vinix/build/../3rdparty/wget/lib/c-strcasecmp.c:49:7: error: 'UCHAR_MAX' undeclared (first use in this function)
   49 |   if (UCHAR_MAX <= INT_MAX)
      |       ^~~~~~~
/home/wilsonk/Downloads/vinix/build/../3rdparty/wget/lib/c-strcasecmp.c:25:1: note: 'UCHAR_MAX' is defined in header '<limits.h>'; did you forget to '#include <limits.h>'?
   24 | #include "c-ctype.h"
  +++ |+#include <limits.h>
   25 | 
/home/wilsonk/Downloads/vinix/build/../3rdparty/wget/lib/c-strcasecmp.c:49:7: note: each undeclared identifier is reported only once for each function it appears in
   49 |   if (UCHAR_MAX <= INT_MAX)
      |       ^~~~~~~~~
/home/wilsonk/Downloads/vinix/build/../3rdparty/wget/lib/c-strcasecmp.c:49:20: error: 'INT_MAX' undeclared (first use in this function)
   49 |   if (UCHAR_MAX <= INT_MAX)
      |                    ^~~~~~~
/home/wilsonk/Downloads/vinix/build/../3rdparty/wget/lib/c-strcasecmp.c:49:20: note: 'INT_MAX' is defined in header '<limits.h>'; did you forget to '#include <limits.h>'?
```
I tried to just remove the wget directory and maybe get things built that way, but I ran into some similar errors with another package. Not sure why this is happening, but it is a bit of a show stopper :)

Any suggestions?
